**Install Library Apyori**

In [1]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=b1681653b2a447521aa1f703b7ee3e1ec21e349f86ecdbb81848a3e19e8cc52a
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

**Impor library Numpy, Pandas dan Apyori**

In [2]:
import numpy as np
import pandas as pd
from apyori import apriori

**Tambahkan file Assignment-1_Data.xlsx**

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Assignment-1_Data.xlsx to Assignment-1_Data.xlsx

**Panggil data yang telah ditambahkan**

In [4]:
data = pd.read_excel('Assignment-1_Data.xlsx')
data.head()

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

**Cek Ukuran data**

In [5]:
data.shape

(522064, 7)

**Mengambil isi data dan menjadikan dalam bentuk tipe data list**

In [6]:
records = []
for i in range(0, 20):
  records.append([str(data.values[i,j]) for j in range(0, 6)])

In [7]:
print(records)

[['536365', 'WHITE HANGING HEART T-LIGHT HOLDER', '6', '2010-12-01 08:26:00', '2.55', '17850.0'], ['536365', 'WHITE METAL LANTERN', '6', '2010-12-01 08:26:00', '3.39', '17850.0'], ['536365', 'CREAM CUPID HEARTS COAT HANGER', '8', '2010-12-01 08:26:00', '2.75', '17850.0'], ['536365', 'KNITTED UNION FLAG HOT WATER BOTTLE', '6', '2010-12-01 08:26:00', '3.39', '17850.0'], ['536365', 'RED WOOLLY HOTTIE WHITE HEART.', '6', '2010-12-01 08:26:00', '3.39', '17850.0'], ['536365', 'SET 7 BABUSHKA NESTING BOXES', '2', '2010-12-01 08:26:00', '7.65', '17850.0'], ['536365', 'GLASS STAR FROSTED T-LIGHT HOLDER', '6', '2010-12-01 08:26:00', '4.25', '17850.0'], ['536366', 'HAND WARMER UNION JACK', '6', '2010-12-01 08:28:00', '1.85', '17850.0'], ['536366', 'HAND WARMER RED POLKA DOT', '6', '2010-12-01 08:28:00', '1.85', '17850.0'], ['536367', 'ASSORTED COLOUR BIRD ORNAMENT', '32', '2010-12-01 08:34:00', '1.69', '13047.0'], ['536367', "POPPY'S PLAYHOUSE BEDROOM", '6', '2010-12-01 08:34:00', '2.1', '13047.0'], ['536367', "POPPY'S PLAYHOUSE KITCHEN", '6', '2010-12-01 08:34:00', '2.1', '13047.0'], ['536367', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', '8', '2010-12-01 08:34:00', '3.75', '13047.0'], ['536367', 'IVORY KNITTED MUG COSY', '6', '2010-12-01 08:34:00', '1.65', '13047.0'], ['536367', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', '6', '2010-12-01 08:34:00', '4.25', '13047.0'], ['536367', 'BOX OF VINTAGE JIGSAW BLOCKS', '3', '2010-12-01 08:34:00', '4.95', '13047.0'], ['536367', 'BOX OF VINTAGE ALPHABET BLOCKS', '2', '2010-12-01 08:34:00', '9.95', '13047.0'], ['536367', 'HOME BUILDING BLOCK WORD', '3', '2010-12-01 08:34:00', '5.95', '13047.0'], ['536367', 'LOVE BUILDING BLOCK WORD', '3', '2010-12-01 08:34:00', '5.95', '13047.0'], ['536367', 'RECIPE BOX WITH METAL HEART', '4', '2010-12-01 08:34:00', '7.95', '13047.0']]

**Jalankan metode apriori untuk mendapatkan rule**

In [8]:
association_rules = apriori(records,
                            min_support=0.1,
                            min_confidence=0.2,
                            min_lift=1.0,
                            min_length=2)
association_results = list(association_rules)

**Lihat rule yang terbentuk**

In [10]:
assoc_rule = list(association_results)
print(assoc_rule)

[RelationRecord(items=frozenset({'13047.0'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'13047.0'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'17850.0'}), support=0.45, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'17850.0'}), confidence=0.45, lift=1.0)]), RelationRecord(items=frozenset({'2010-12-01 08:26:00'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:26:00'}), confidence=0.35, lift=1.0)]), RelationRecord(items=frozenset({'2010-12-01 08:34:00'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'536365'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'536365'}), confidence=0.35, lift=1.0)]), RelationRecord(items=frozenset({'536367'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'536367'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'6'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'6'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'17850.0', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'1.85'}), confidence=0.22222222222222224, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'2010-12-01 08:28:00', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'536366', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'536366'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'6', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '2.1'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '2010-12-01 08:34:00'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'13047.0', '2010-12-01 08:34:00'}), confidence=0.55, lift=1.0), OrderedStatistic(items_base=frozenset({'13047.0'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'2010-12-01 08:34:00'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '3'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'13047.0'}), items_add=frozenset({'3'}), confidence=0.2727272727272727, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'3'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '5.95'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'5.95'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '536367'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'13047.0', '536367'}), confidence=0.55, lift=1.0), OrderedStatistic(items_base=frozenset({'13047.0'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'536367'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '6'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'13047.0', '6'}), confidence=0.2, lift=1.0)]), RelationRecord(items=frozenset({'17850.0', '2010-12-01 08:26:00'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'17850.0', '2010-12-01 08:26:00'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'2010-12-01 08:26:00'}), confidence=0.7777777777777777, lift=2.222222222222222), OrderedStatistic(items_base=frozenset({'2010-12-01 08:26:00'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'17850.0', '2010-12-01 08:28:00'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=0.22222222222222224, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'17850.0', '3.39'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'3.39'}), confidence=0.3333333333333333, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'3.39'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'17850.0', '536365'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'17850.0', '536365'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'536365'}), confidence=0.7777777777777777, lift=2.222222222222222), OrderedStatistic(items_base=frozenset({'536365'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'536366', '17850.0'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'536366'}), confidence=0.22222222222222224, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223)]), RelationRecord(items=frozenset({'17850.0', '6'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'17850.0', '6'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'6'}), confidence=0.7777777777777777, lift=1.414141414141414), OrderedStatistic(items_base=frozenset({'6'}), items_add=frozenset({'17850.0'}), confidence=0.6363636363636362, lift=1.414141414141414)]), RelationRecord(items=frozenset({'2010-12-01 08:34:00', '2.1'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'2.1', '536367'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'2.1', '6'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'2010-12-01 08:26:00', '3.39'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2010-12-01 08:26:00'}), items_add=frozenset({'3.39'}), confidence=0.4285714285714286, lift=2.8571428571428577), OrderedStatistic(items_base=frozenset({'3.39'}), items_add=frozenset({'2010-12-01 08:26:00'}), confidence=1.0, lift=2.857142857142857)]), RelationRecord(items=frozenset({'2010-12-01 08:26:00', '536365'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:26:00', '536365'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:26:00'}), items_add=frozenset({'536365'}), confidence=1.0, lift=2.857142857142857), OrderedStatistic(items_base=frozenset({'536365'}), items_add=frozenset({'2010-12-01 08:26:00'}), confidence=1.0, lift=2.857142857142857)]), RelationRecord(items=frozenset({'2010-12-01 08:26:00', '6'}), support=0.25, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:26:00', '6'}), confidence=0.25, lift=1.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:26:00'}), items_add=frozenset({'6'}), confidence=0.7142857142857143, lift=1.2987012987012987), OrderedStatistic(items_base=frozenset({'6'}), items_add=frozenset({'2010-12-01 08:26:00'}), confidence=0.45454545454545453, lift=1.2987012987012987)]), RelationRecord(items=frozenset({'536366', '2010-12-01 08:28:00'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'536366'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'2010-12-01 08:28:00', '6'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'3', '2010-12-01 08:34:00'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2010-12-01 08:34:00'}), items_add=frozenset({'3'}), confidence=0.2727272727272727, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'3'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'5.95', '2010-12-01 08:34:00'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'5.95'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'2010-12-01 08:34:00', '536367'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:34:00', '536367'}), confidence=0.55, lift=1.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:34:00'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'536367'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'2010-12-01 08:34:00', '6'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'2010-12-01 08:34:00', '6'}), confidence=0.2, lift=1.0)]), RelationRecord(items=frozenset({'3', '5.95'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3'}), items_add=frozenset({'5.95'}), confidence=0.6666666666666667, lift=6.666666666666667), OrderedStatistic(items_base=frozenset({'5.95'}), items_add=frozenset({'3'}), confidence=1.0, lift=6.666666666666667)]), RelationRecord(items=frozenset({'3', '536367'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'536367'}), items_add=frozenset({'3'}), confidence=0.2727272727272727, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'536365', '3.39'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3.39'}), items_add=frozenset({'536365'}), confidence=1.0, lift=2.857142857142857), OrderedStatistic(items_base=frozenset({'536365'}), items_add=frozenset({'3.39'}), confidence=0.4285714285714286, lift=2.8571428571428577)]), RelationRecord(items=frozenset({'6', '3.39'}), support=0.15, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3.39'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'6'}), items_add=frozenset({'3.39'}), confidence=0.2727272727272727, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'4.25', '6'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'4.25'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'5.95', '536367'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'5.95'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'6', '536365'}), support=0.25, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'6', '536365'}), confidence=0.25, lift=1.0), OrderedStatistic(items_base=frozenset({'536365'}), items_add=frozenset({'6'}), confidence=0.7142857142857143, lift=1.2987012987012987), OrderedStatistic(items_base=frozenset({'6'}), items_add=frozenset({'536365'}), confidence=0.45454545454545453, lift=1.2987012987012987)]), RelationRecord(items=frozenset({'536366', '6'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'6', '536367'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'536367', '6'}), confidence=0.2, lift=1.0)]), RelationRecord(items=frozenset({'17850.0', '2010-12-01 08:28:00', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'17850.0', '2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'2010-12-01 08:28:00', '1.85'}), confidence=0.22222222222222224, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'17850.0', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'17850.0', '1.85'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00', '1.85'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'17850.0', '2010-12-01 08:28:00'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'536366', '17850.0', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'536366', '17850.0'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'536366', '1.85'}), confidence=0.22222222222222224, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'17850.0', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'17850.0', '1.85'}), items_add=frozenset({'536366'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366', '1.85'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'536366', '17850.0'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'17850.0', '6', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'17850.0', '6'}), confidence=1.0, lift=2.857142857142857), OrderedStatistic(items_base=frozenset({'17850.0'}), items_add=frozenset({'6', '1.85'}), confidence=0.22222222222222224, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'17850.0', '1.85'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'6', '1.85'}), items_add=frozenset({'17850.0'}), confidence=1.0, lift=2.2222222222222223), OrderedStatistic(items_base=frozenset({'17850.0', '6'}), items_add=frozenset({'1.85'}), confidence=0.28571428571428575, lift=2.857142857142857)]), RelationRecord(items=frozenset({'536366', '2010-12-01 08:28:00', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'536366', '2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'536366', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'2010-12-01 08:28:00', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00', '1.85'}), items_add=frozenset({'536366'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366', '1.85'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366', '2010-12-01 08:28:00'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'2010-12-01 08:28:00', '6', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'2010-12-01 08:28:00', '6'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00'}), items_add=frozenset({'6', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00', '1.85'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'6', '1.85'}), items_add=frozenset({'2010-12-01 08:28:00'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'2010-12-01 08:28:00', '6'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'536366', '6', '1.85'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1.85'}), items_add=frozenset({'536366', '6'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366'}), items_add=frozenset({'6', '1.85'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366', '1.85'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'6', '1.85'}), items_add=frozenset({'536366'}), confidence=1.0, lift=10.0), OrderedStatistic(items_base=frozenset({'536366', '6'}), items_add=frozenset({'1.85'}), confidence=1.0, lift=10.0)]), RelationRecord(items=frozenset({'13047.0', '2010-12-01 08:34:00', '2.1'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'13047.0', '2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'13047.0', '2.1'}), items_add=frozenset({'2010-12-01 08:34:00'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'2010-12-01 08:34:00', '2.1'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '2.1', '536367'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'13047.0', '536367'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'13047.0', '2.1'}), items_add=frozenset({'536367'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base=frozenset({'2.1', '536367'}), items_add=frozenset({'13047.0'}), confidence=1.0, lift=1.8181818181818181)]), RelationRecord(items=frozenset({'13047.0', '2.1', '6'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2.1'}), items_add=frozenset({'13047.0', '6'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'13047.0', '2.1'}), items_add=frozenset({'6'}), confidence=1.0, lift=1.8181818181818181), OrderedStatistic(items_base

**Lihat banyaknya rule yang terbentuk**

In [11]:
print(len(assoc_rule))

107

**Rule yang terbentuk lebih detail**

In [12]:
for item in assoc_rule:
    pair = item[0]
    items = [x for x in pair]

    if len(items) > 1:
        print("Rule: " + items[0] + " -> " + items[1])
        print("Support: " + str(item[1]))

Rule: 17850.0 -> 1.85
Support: 0.1
Rule: 2010-12-01 08:28:00 -> 1.85
Support: 0.1
Rule: 536366 -> 1.85
Support: 0.1
Rule: 6 -> 1.85
Support: 0.1
Rule: 13047.0 -> 2.1
Support: 0.1
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.55
Rule: 13047.0 -> 3
Support: 0.15
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 536367
Support: 0.55
Rule: 13047.0 -> 6
Support: 0.2
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.35
Rule: 17850.0 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 17850.0 -> 3.39
Support: 0.15
Rule: 17850.0 -> 536365
Support: 0.35
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 17850.0 -> 6
Support: 0.35
Rule: 2010-12-01 08:34:00 -> 2.1
Support: 0.1
Rule: 2.1 -> 536367
Support: 0.1
Rule: 2.1 -> 6
Support: 0.1
Rule: 2010-12-01 08:26:00 -> 3.39
Support: 0.15
Rule: 2010-12-01 08:26:00 -> 536365
Support: 0.35
Rule: 2010-12-01 08:26:00 -> 6
Support: 0.25
Rule: 536366 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 2010-12-01 08:28:00 -> 6
Support: 0.1
Rule: 3 -> 2010-12-01 08:34:00
Support: 0.15
Rule: 5.95 -> 2010-12-01 08:34:00
Support: 0.1
Rule: 2010-12-01 08:34:00 -> 536367
Support: 0.55
Rule: 2010-12-01 08:34:00 -> 6
Support: 0.2
Rule: 3 -> 5.95
Support: 0.1
Rule: 3 -> 536367
Support: 0.15
Rule: 536365 -> 3.39
Support: 0.15
Rule: 6 -> 3.39
Support: 0.15
Rule: 4.25 -> 6
Support: 0.1
Rule: 5.95 -> 536367
Support: 0.1
Rule: 6 -> 536365
Support: 0.25
Rule: 536366 -> 6
Support: 0.1
Rule: 6 -> 536367
Support: 0.2
Rule: 17850.0 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 17850.0 -> 6
Support: 0.1
Rule: 536366 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 2010-12-01 08:28:00 -> 6
Support: 0.1
Rule: 536366 -> 6
Support: 0.1
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.1
Rule: 13047.0 -> 2.1
Support: 0.1
Rule: 13047.0 -> 2.1
Support: 0.1
Rule: 13047.0 -> 3
Support: 0.15
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.55
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.2
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 3
Support: 0.15
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 6
Support: 0.2
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.15
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.35
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.25
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 17850.0 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 17850.0 -> 536365
Support: 0.15
Rule: 17850.0 -> 6
Support: 0.15
Rule: 17850.0 -> 6
Support: 0.25
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 2010-12-01 08:34:00 -> 2.1
Support: 0.1
Rule: 2010-12-01 08:34:00 -> 2.1
Support: 0.1
Rule: 6 -> 2.1
Support: 0.1
Rule: 2010-12-01 08:26:00 -> 3.39
Support: 0.15
Rule: 2010-12-01 08:26:00 -> 6
Support: 0.15
Rule: 2010-12-01 08:26:00 -> 6
Support: 0.25
Rule: 536366 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 3 -> 5.95
Support: 0.1
Rule: 3 -> 2010-12-01 08:34:00
Support: 0.15
Rule: 5.95 -> 2010-12-01 08:34:00
Support: 0.1
Rule: 6 -> 2010-12-01 08:34:00
Support: 0.2
Rule: 3 -> 5.95
Support: 0.1
Rule: 536365 -> 6
Support: 0.15
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 17850.0 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 536366 -> 2010-12-01 08:28:00
Support: 0.1
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.1
Rule: 13047.0 -> 2010-12-01 08:34:00
Support: 0.1
Rule: 13047.0 -> 6
Support: 0.1
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 3
Support: 0.15
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 13047.0 -> 6
Support: 0.2
Rule: 13047.0 -> 5.95
Support: 0.1
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.15
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.15
Rule: 17850.0 -> 2010-12-01 08:26:00
Support: 0.25
Rule: 536366 -> 17850.0
Support: 0.1
Rule: 17850.0 -> 536365
Support: 0.15
Rule: 2010-12-01 08:34:00 -> 6
Support: 0.1
Rule: 2010-12-01 08:26:00 -> 6
Support: 0.15
Rule: 3 -> 5.95
Support: 0.1
Rule: 2010-12-01 08:28:00 -> 1.85
Support: 0.1
Rule: 536367 -> 2.1
Support: 0.1
Rule: 5.95 -> 536367
Support: 0.1
Rule: 2010-12-01 08:26:00 -> 536365
Support: 0.15

In [13]:
print("confidence: " + str(item[2][0][2]))
print("Lift: " + str(item[2][0][3]))

confidence: 0.3333333333333333
Lift: 2.2222222222222223

**PERCOBAAN 2**

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=07bc3b91ec5f7d5c2cb4cd8c059a9d16bc370683a14437632ba3b09f4ec3d45d
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import numpy as np
import pandas as pd
from apyori import apriori

**Tambahkan file data_AR.xlxs**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Groceries_dataset.csv to Groceries_dataset (1).csv

**Panggil data yang telah ditambahkan**

In [ ]:
data = pd.read_csv('Groceries_dataset.csv')
data.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

**Cek Ukuran data**

In [ ]:
data.shape

(38765, 3)

**Mengambil isi data dan menjadikan dalam bentuk tipe data list**

In [ ]:
records = []
for i in range(0, 6):
  records.append([str(data.values[i,j]) for j in range(0, 3)])

In [ ]:
print(records)

[['1808', '21-07-2015', 'tropical fruit'], ['2552', '05-01-2015', 'whole milk'], ['2300', '19-09-2015', 'pip fruit'], ['1187', '12-12-2015', 'other vegetables'], ['3037', '01-02-2015', 'whole milk'], ['4941', '14-02-2015', 'rolls/buns']]

**Jalankan metode apriori untuk mendapatkan rule**

In [ ]:
association_rules = apriori(records,
                            min_support=0.1,
                            min_confidence=0.2,
                            min_lift=1.0,
                            min_length=2)
association_results = list(association_rules)

**Lihat rule yang terbentuk**

In [ ]:
assoc_rule = list(association_results)
print(assoc_rule)

[RelationRecord(items=frozenset({'whole milk'}), support=0.3333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole milk'}), confidence=0.3333333333333333, lift=1.0)]), RelationRecord(items=frozenset({'01-02-2015', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'01-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '01-02-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'01-02-2015'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'05-01-2015', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'05-01-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '05-01-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'05-01-2015'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'1187', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '1187'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'14-02-2015', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'rolls/buns', '14-02-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'1808', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '1808'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', '19-09-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'19-09-2015', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'2552'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'whole milk', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'3037'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'rolls/buns', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '01-02-2015', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'whole milk', '3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'whole milk', '01-02-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'01-02-2015', '3037'}), confidence=0.5, lift=3.0), OrderedStatistic(items_base=frozenset({'01-02-2015', '3037'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk', '01-02-2015'}), items_add=frozenset({'3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk', '3037'}), items_add=frozenset({'01-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '05-01-2015', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'whole milk', '2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'whole milk', '05-01-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'05-01-2015', '2552'}), confidence=0.5, lift=3.0), OrderedStatistic(items_base=frozenset({'05-01-2015', '2552'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk', '05-01-2015'}), items_add=frozenset({'2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk', '2552'}), items_add=frozenset({'05-01-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '1187', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'other vegetables', '12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'other vegetables', '1187'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'1187', '12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'1187', '12-12-2015'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables', '1187'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables', '12-12-2015'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'rolls/buns', '14-02-2015', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'rolls/buns', '4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'rolls/buns', '14-02-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'14-02-2015', '4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'14-02-2015', '4941'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns', '14-02-2015'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns', '4941'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '1808', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'tropical fruit', '21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'tropical fruit', '1808'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'1808', '21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'1808', '21-07-2015'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit', '1808'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit', '21-07-2015'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', '19-09-2015', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'2300', 'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'19-09-2015', 'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'2300', '19-09-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300', '19-09-2015'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'19-09-2015', 'pip fruit'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300', 'pip fruit'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)])]

**Lihat banyaknya rule yang terbentuk**

In [ ]:
print(len(assoc_rule))

25

**Rule yang terbentuk lebih detail**

In [ ]:
for item in assoc_rule:
    pair = item[0]
    items = [x for x in pair]

    if len(items) > 1:
        print("Rule: " + items[0] + " -> " + items[1])
        print("Support: " + str(item[1]))

Rule: 01-02-2015 -> 3037
Support: 0.16666666666666666
Rule: whole milk -> 01-02-2015
Support: 0.16666666666666666
Rule: 05-01-2015 -> 2552
Support: 0.16666666666666666
Rule: whole milk -> 05-01-2015
Support: 0.16666666666666666
Rule: 1187 -> 12-12-2015
Support: 0.16666666666666666
Rule: other vegetables -> 1187
Support: 0.16666666666666666
Rule: other vegetables -> 12-12-2015
Support: 0.16666666666666666
Rule: 14-02-2015 -> 4941
Support: 0.16666666666666666
Rule: rolls/buns -> 14-02-2015
Support: 0.16666666666666666
Rule: 1808 -> 21-07-2015
Support: 0.16666666666666666
Rule: tropical fruit -> 1808
Support: 0.16666666666666666
Rule: 2300 -> 19-09-2015
Support: 0.16666666666666666
Rule: 19-09-2015 -> pip fruit
Support: 0.16666666666666666
Rule: tropical fruit -> 21-07-2015
Support: 0.16666666666666666
Rule: 2300 -> pip fruit
Support: 0.16666666666666666
Rule: whole milk -> 2552
Support: 0.16666666666666666
Rule: whole milk -> 3037
Support: 0.16666666666666666
Rule: rolls/buns -> 4941
Support: 0.16666666666666666
Rule: whole milk -> 01-02-2015
Support: 0.16666666666666666
Rule: whole milk -> 05-01-2015
Support: 0.16666666666666666
Rule: other vegetables -> 1187
Support: 0.16666666666666666
Rule: rolls/buns -> 14-02-2015
Support: 0.16666666666666666
Rule: tropical fruit -> 1808
Support: 0.16666666666666666
Rule: 2300 -> 19-09-2015
Support: 0.16666666666666666

In [ ]:
print("confidence: " + str(item[2][0][2]))
print("Lift: " + str(item[2][0][3]))

confidence: 1.0
Lift: 6.0