**PERCOBAAN 1**

**Install Library Apyori**

In [2]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=7c521f4094a4f723e569baf6f4e6f63aa1248559ecbd52bb2cddf3a64a59f6fe
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

**Impor library Numpy, Pandas dan Apyori**

In [3]:
import numpy as np
import pandas as pd
from apyori import apriori

**Tambahkan file data_AR.xlxs**

In [4]:
from google.colab import files
uploaded = files.upload()

Saving data_AR.xlsx to data_AR.xlsx

**Panggil data yang telah ditambahkan**

In [5]:
data = pd.read_excel('data_AR.xlsx')
data.head()

   wine  Chips  bread  butter  milk  Apple
0  wine    NaN  bread  butter  milk    NaN
1   NaN    NaN  bread  butter  milk    NaN
2   NaN  Chips    NaN     NaN   NaN  Apple
3  wine  Chips  bread  butter  milk  Apple
4  wine  Chips    NaN     NaN  milk    NaN

**Cek Ukuran data**

In [6]:
data.shape

(21, 6)

**Mengambil isi data dan menjadikan dalam bentuk tipe data list**

In [7]:
records = []
for i in range(0, 20):
  records.append([str(data.values[i,j]) for j in range(0, 6)])

In [8]:
print(records)

[['wine', 'nan', 'bread', 'butter', 'milk', 'nan'], ['nan', 'nan', 'bread', 'butter', 'milk', 'nan'], ['nan', 'Chips', 'nan', 'nan', 'nan', 'Apple'], ['wine', 'Chips', 'bread', 'butter', 'milk', 'Apple'], ['wine', 'Chips', 'nan', 'nan', 'milk', 'nan'], ['wine', 'Chips', 'bread', 'butter', 'nan', 'Apple'], ['wine', 'Chips', 'nan', 'nan', 'milk', 'nan'], ['wine', 'nan', 'bread', 'nan', 'nan', 'Apple'], ['wine', 'nan', 'bread', 'butter', 'milk', 'Apple'], ['nan', 'Chips', 'bread', 'butter', 'nan', 'Apple'], ['wine', 'nan', 'nan', 'butter', 'milk', 'nan'], ['wine', 'Chips', 'bread', 'butter', 'milk', 'Apple'], ['wine', 'nan', 'bread', 'nan', 'milk', 'Apple'], ['wine', 'nan', 'bread', 'butter', 'milk', 'Apple'], ['wine', 'Chips', 'bread', 'butter', 'milk', 'Apple'], ['nan', 'Chips', 'bread', 'butter', 'milk', 'Apple'], ['nan', 'Chips', 'nan', 'butter', 'milk', 'Apple'], ['wine', 'Chips', 'bread', 'butter', 'milk', 'Apple'], ['wine', 'nan', 'bread', 'butter', 'milk', 'Apple'], ['wine', 'Chips', 'bread', 'nan', 'milk', 'Apple']]

**Jalankan metode apriori untuk mendapatkan rule**

In [28]:
association_rules = apriori(records,
                            min_support=0.1,
                            min_confidence=0.2,
                            min_lift=1.0,
                            min_length=2)
association_results = list(association_rules)

**Lihat rule yang terbentuk**

In [35]:
assoc_rule = list(association_results)
print(assoc_rule)

[RelationRecord(items=frozenset({'Apple'}), support=0.75, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple'}), confidence=0.75, lift=1.0)]), RelationRecord(items=frozenset({'Chips'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips'}), confidence=0.6, lift=1.0)]), RelationRecord(items=frozenset({'bread'}), support=0.75, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'bread'}), confidence=0.75, lift=1.0)]), RelationRecord(items=frozenset({'butter'}), support=0.7, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'butter'}), confidence=0.7, lift=1.0)]), RelationRecord(items=frozenset({'milk'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk'}), confidence=0.8, lift=1.0)]), RelationRecord(items=frozenset({'nan'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.8, lift=1.0)]), RelationRecord(items=frozenset({'wine'}), support=0.75, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine'}), confidence=0.75, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'Apple'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'Apple'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'Chips'}), confidence=0.6666666666666666, lift=1.1111111111111112), OrderedStatistic(items_base=frozenset({'Chips'}), items_add=frozenset({'Apple'}), confidence=0.8333333333333334, lift=1.1111111111111112)]), RelationRecord(items=frozenset({'Apple', 'bread'}), support=0.65, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'bread'}), confidence=0.65, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'bread'}), confidence=0.8666666666666667, lift=1.1555555555555557), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'Apple'}), confidence=0.8666666666666667, lift=1.1555555555555557)]), RelationRecord(items=frozenset({'Apple', 'butter'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'butter'}), confidence=0.55, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'butter'}), confidence=0.7333333333333334, lift=1.0476190476190477), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'Apple'}), confidence=0.7857142857142858, lift=1.0476190476190477)]), RelationRecord(items=frozenset({'Apple', 'milk'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'milk'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Apple'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Apple'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Apple'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Apple'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'bread'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'bread'}), confidence=0.4, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'butter'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'butter'}), confidence=0.4, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'milk'}), support=0.45, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'milk'}), confidence=0.45, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Chips'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Chips'}), confidence=0.4, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Chips'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Chips'}), confidence=0.4, lift=1.0)]), RelationRecord(items=frozenset({'butter', 'bread'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'butter', 'bread'}), confidence=0.6, lift=1.0), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'butter'}), confidence=0.7999999999999999, lift=1.1428571428571428), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'bread'}), confidence=0.8571428571428572, lift=1.142857142857143)]), RelationRecord(items=frozenset({'milk', 'bread'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk', 'bread'}), confidence=0.6, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'bread'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'bread'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'bread'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'bread'}), confidence=0.6, lift=1.0), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'wine'}), confidence=0.7999999999999999, lift=1.0666666666666667), OrderedStatistic(items_base=frozenset({'wine'}), items_add=frozenset({'bread'}), confidence=0.7999999999999999, lift=1.0666666666666667)]), RelationRecord(items=frozenset({'milk', 'butter'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'milk', 'butter'}), confidence=0.6, lift=1.0), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'milk'}), confidence=0.8571428571428572, lift=1.0714285714285714), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'butter'}), confidence=0.7499999999999999, lift=1.0714285714285714)]), RelationRecord(items=frozenset({'nan', 'butter'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'butter'}), confidence=0.5, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'butter'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'butter'}), confidence=0.5, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'milk'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'milk'}), confidence=0.6, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'milk'}), support=0.65, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'milk'}), confidence=0.65, lift=1.0), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'wine'}), confidence=0.8125, lift=1.0833333333333333), OrderedStatistic(items_base=frozenset({'wine'}), items_add=frozenset({'milk'}), confidence=0.8666666666666667, lift=1.0833333333333333)]), RelationRecord(items=frozenset({'nan', 'wine'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'wine'}), confidence=0.55, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'Apple', 'bread'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'bread', 'Apple'}), confidence=0.4, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'Chips', 'bread'}), confidence=0.5333333333333333, lift=1.3333333333333333), OrderedStatistic(items_base=frozenset({'Chips'}), items_add=frozenset({'Apple', 'bread'}), confidence=0.6666666666666667, lift=1.0256410256410258), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'Chips', 'Apple'}), confidence=0.5333333333333333, lift=1.0666666666666667), OrderedStatistic(items_base=frozenset({'Chips', 'Apple'}), items_add=frozenset({'bread'}), confidence=0.8, lift=1.0666666666666667), OrderedStatistic(items_base=frozenset({'Apple', 'bread'}), items_add=frozenset({'Chips'}), confidence=0.6153846153846154, lift=1.0256410256410258), OrderedStatistic(items_base=frozenset({'Chips', 'bread'}), items_add=frozenset({'Apple'}), confidence=1.0, lift=1.3333333333333333)]), RelationRecord(items=frozenset({'Chips', 'Apple', 'butter'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'butter', 'Apple'}), confidence=0.4, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'Chips', 'butter'}), confidence=0.5333333333333333, lift=1.3333333333333333), OrderedStatistic(items_base=frozenset({'Chips'}), items_add=frozenset({'Apple', 'butter'}), confidence=0.6666666666666667, lift=1.2121212121212122), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'Chips', 'Apple'}), confidence=0.5714285714285715, lift=1.142857142857143), OrderedStatistic(items_base=frozenset({'Chips', 'Apple'}), items_add=frozenset({'butter'}), confidence=0.8, lift=1.142857142857143), OrderedStatistic(items_base=frozenset({'Apple', 'butter'}), items_add=frozenset({'Chips'}), confidence=0.7272727272727273, lift=1.2121212121212122), OrderedStatistic(items_base=frozenset({'Chips', 'butter'}), items_add=frozenset({'Apple'}), confidence=1.0, lift=1.3333333333333333)]), RelationRecord(items=frozenset({'Chips', 'Apple', 'milk'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'milk', 'Apple'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'Chips', 'milk'}), confidence=0.4666666666666666, lift=1.037037037037037), OrderedStatistic(items_base=frozenset({'Chips'}), items_add=frozenset({'Apple', 'milk'}), confidence=0.5833333333333334, lift=1.0606060606060606), OrderedStatistic(items_base=frozenset({'Apple', 'milk'}), items_add=frozenset({'Chips'}), confidence=0.6363636363636362, lift=1.0606060606060606), OrderedStatistic(items_base=frozenset({'Chips', 'milk'}), items_add=frozenset({'Apple'}), confidence=0.7777777777777777, lift=1.037037037037037)]), RelationRecord(items=frozenset({'nan', 'Chips', 'Apple'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Chips', 'Apple'}), confidence=0.3, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'Apple', 'wine'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Chips', 'Apple'}), confidence=0.3, lift=1.0)]), RelationRecord(items=frozenset({'Apple', 'butter', 'bread'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'butter', 'bread'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'butter', 'bread'}), confidence=0.6666666666666666, lift=1.1111111111111112), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'Apple', 'butter'}), confidence=0.6666666666666666, lift=1.212121212121212), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'Apple', 'bread'}), confidence=0.7142857142857143, lift=1.098901098901099), OrderedStatistic(items_base=frozenset({'Apple', 'bread'}), items_add=frozenset({'butter'}), confidence=0.7692307692307692, lift=1.0989010989010988), OrderedStatistic(items_base=frozenset({'Apple', 'butter'}), items_add=frozenset({'bread'}), confidence=0.9090909090909091, lift=1.2121212121212122), OrderedStatistic(items_base=frozenset({'butter', 'bread'}), items_add=frozenset({'Apple'}), confidence=0.8333333333333334, lift=1.1111111111111112)]), RelationRecord(items=frozenset({'Apple', 'milk', 'bread'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'milk', 'bread'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'milk', 'bread'}), confidence=0.6666666666666666, lift=1.1111111111111112), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'Apple', 'milk'}), confidence=0.6666666666666666, lift=1.212121212121212), OrderedStatistic(items_base=frozenset({'Apple', 'milk'}), items_add=frozenset({'bread'}), confidence=0.9090909090909091, lift=1.2121212121212122), OrderedStatistic(items_base=frozenset({'milk', 'bread'}), items_add=frozenset({'Apple'}), confidence=0.8333333333333334, lift=1.1111111111111112)]), RelationRecord(items=frozenset({'nan', 'Apple', 'bread'}), support=0.45, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Apple', 'bread'}), confidence=0.45, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'nan', 'bread'}), confidence=0.6, lift=1.0909090909090908), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'nan', 'Apple'}), confidence=0.6, lift=1.0909090909090908), OrderedStatistic(items_base=frozenset({'nan', 'Apple'}), items_add=frozenset({'bread'}), confidence=0.8181818181818181, lift=1.0909090909090908), OrderedStatistic(items_base=frozenset({'nan', 'bread'}), items_add=frozenset({'Apple'}), confidence=0.8181818181818181, lift=1.0909090909090908)]), RelationRecord(items=frozenset({'wine', 'Apple', 'bread'}), support=0.55, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Apple', 'bread'}), confidence=0.55, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'wine', 'bread'}), confidence=0.7333333333333334, lift=1.2222222222222223), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'wine', 'Apple'}), confidence=0.7333333333333334, lift=1.3333333333333333), OrderedStatistic(items_base=frozenset({'wine'}), items_add=frozenset({'Apple', 'bread'}), confidence=0.7333333333333334, lift=1.1282051282051282), OrderedStatistic(items_base=frozenset({'Apple', 'bread'}), items_add=frozenset({'wine'}), confidence=0.8461538461538461, lift=1.1282051282051282), OrderedStatistic(items_base=frozenset({'wine', 'Apple'}), items_add=frozenset({'bread'}), confidence=1.0, lift=1.3333333333333333), OrderedStatistic(items_base=frozenset({'wine', 'bread'}), items_add=frozenset({'Apple'}), confidence=0.9166666666666667, lift=1.2222222222222223)]), RelationRecord(items=frozenset({'Apple', 'milk', 'butter'}), support=0.45, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Apple', 'milk', 'butter'}), confidence=0.45, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'milk', 'butter'}), confidence=0.6, lift=1.0), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'Apple', 'milk'}), confidence=0.6428571428571429, lift=1.1688311688311688), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'Apple', 'butter'}), confidence=0.5625, lift=1.0227272727272727), OrderedStatistic(items_base=frozenset({'Apple', 'butter'}), items_add=frozenset({'milk'}), confidence=0.8181818181818181, lift=1.0227272727272725), OrderedStatistic(items_base=frozenset({'Apple', 'milk'}), items_add=frozenset({'butter'}), confidence=0.8181818181818181, lift=1.1688311688311688), OrderedStatistic(items_base=frozenset({'milk', 'butter'}), items_add=frozenset({'Apple'}), confidence=0.75, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Apple', 'butter'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Apple', 'butter'}), confidence=0.35, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Apple', 'butter'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Apple', 'butter'}), confidence=0.4, lift=1.0), OrderedStatistic(items_base=frozenset({'Apple'}), items_add=frozenset({'wine', 'butter'}), confidence=0.5333333333333333, lift=1.0666666666666667), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'wine', 'Apple'}), confidence=0.5714285714285715, lift=1.038961038961039), OrderedStatistic(items_base=frozenset({'wine', 'Apple'}), items_add=frozenset({'butter'}), confidence=0.7272727272727273, lift=1.038961038961039), OrderedStatistic(items_base=frozenset({'wine', 'butter'}), items_add=frozenset({'Apple'}), confidence=0.8, lift=1.0666666666666667)]), RelationRecord(items=frozenset({'nan', 'Apple', 'milk'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Apple', 'milk'}), confidence=0.35, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Apple', 'milk'}), support=0.45, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Apple', 'milk'}), confidence=0.45, lift=1.0), OrderedStatistic(items_base=frozenset({'milk'}), items_add=frozenset({'wine', 'Apple'}), confidence=0.5625, lift=1.0227272727272727), OrderedStatistic(items_base=frozenset({'wine'}), items_add=frozenset({'Apple', 'milk'}), confidence=0.6, lift=1.0909090909090908), OrderedStatistic(items_base=frozenset({'Apple', 'milk'}), items_add=frozenset({'wine'}), confidence=0.8181818181818181, lift=1.0909090909090908), OrderedStatistic(items_base=frozenset({'wine', 'Apple'}), items_add=frozenset({'milk'}), confidence=0.8181818181818181, lift=1.0227272727272725)]), RelationRecord(items=frozenset({'nan', 'wine', 'Apple'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'wine', 'Apple'}), confidence=0.35, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'butter', 'bread'}), support=0.35, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'butter', 'bread'}), confidence=0.35, lift=1.0), OrderedStatistic(items_base=frozenset({'bread'}), items_add=frozenset({'Chips', 'butter'}), confidence=0.4666666666666666, lift=1.1666666666666665), OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'Chips', 'bread'}), confidence=0.5, lift=1.25), OrderedStatistic(items_base=frozenset({'Chips', 'bread'}), items_add=frozenset({'butter'}), confidence=0.8749999999999999, lift=1.25), OrderedStatistic(items_base=frozenset({'Chips', 'butter'}), items_add=frozenset({'bread'}), confidence=0.8749999999999999, lift=1.1666666666666665)]), RelationRecord(items=frozenset({'Chips', 'milk', 'bread'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'milk', 'bread'}), confidence=0.3, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Chips', 'bread'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Chips', 'bread'}), confidence=0.2, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Chips', 'bread'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Chips', 'bread'}), confidence=0.3, lift=1.0)]), RelationRecord(items=frozenset({'Chips', 'milk', 'butter'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'Chips', 'milk', 'butter'}), confidence=0.3, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Chips', 'butter'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Chips', 'butter'}), confidence=0.2, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Chips', 'butter'}), support=0.25, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'wine', 'Chips', 'butter'}), confidence=0.25, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Chips', 'milk'}), support=0.25, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan', 'Chips', 'milk'}), confidence=0.25, lift=1.0)]), RelationRecord(items=frozenset({'wine', 'Chips', 'milk'}), support=0.35, ordered_statistics=[OrderedStatistic(items_

**Lihat banyaknya rule yang terbentuk**

In [37]:
print(len(assoc_rule))

107

**Rule yang terbentuk lebih detail**

In [44]:
for item in assoc_rule:
    pair = item[0]
    items = [x for x in pair]

    if len(items) > 1:
        print("Rule: " + items[0] + " -> " + items[1])
        print("Support: " + str(item[1]))

Rule: Chips -> Apple
Support: 0.5
Rule: Apple -> bread
Support: 0.65
Rule: Apple -> butter
Support: 0.55
Rule: Apple -> milk
Support: 0.55
Rule: nan -> Apple
Support: 0.55
Rule: wine -> Apple
Support: 0.55
Rule: Chips -> bread
Support: 0.4
Rule: Chips -> butter
Support: 0.4
Rule: Chips -> milk
Support: 0.45
Rule: nan -> Chips
Support: 0.4
Rule: wine -> Chips
Support: 0.4
Rule: butter -> bread
Support: 0.6
Rule: milk -> bread
Support: 0.6
Rule: nan -> bread
Support: 0.55
Rule: wine -> bread
Support: 0.6
Rule: milk -> butter
Support: 0.6
Rule: nan -> butter
Support: 0.5
Rule: wine -> butter
Support: 0.5
Rule: nan -> milk
Support: 0.6
Rule: wine -> milk
Support: 0.65
Rule: nan -> wine
Support: 0.55
Rule: Chips -> Apple
Support: 0.4
Rule: Chips -> Apple
Support: 0.4
Rule: Chips -> Apple
Support: 0.35
Rule: nan -> Chips
Support: 0.3
Rule: Chips -> Apple
Support: 0.3
Rule: Apple -> butter
Support: 0.5
Rule: Apple -> milk
Support: 0.5
Rule: nan -> Apple
Support: 0.45
Rule: wine -> Apple
Support: 0.55
Rule: Apple -> milk
Support: 0.45
Rule: nan -> Apple
Support: 0.35
Rule: wine -> Apple
Support: 0.4
Rule: nan -> Apple
Support: 0.35
Rule: wine -> Apple
Support: 0.45
Rule: nan -> wine
Support: 0.35
Rule: Chips -> butter
Support: 0.35
Rule: Chips -> milk
Support: 0.3
Rule: nan -> Chips
Support: 0.2
Rule: wine -> Chips
Support: 0.3
Rule: Chips -> milk
Support: 0.3
Rule: nan -> Chips
Support: 0.2
Rule: wine -> Chips
Support: 0.25
Rule: nan -> Chips
Support: 0.25
Rule: wine -> Chips
Support: 0.35
Rule: nan -> wine
Support: 0.2
Rule: milk -> butter
Support: 0.5
Rule: nan -> butter
Support: 0.4
Rule: wine -> butter
Support: 0.45
Rule: nan -> milk
Support: 0.4
Rule: wine -> milk
Support: 0.5
Rule: nan -> wine
Support: 0.4
Rule: nan -> milk
Support: 0.4
Rule: wine -> milk
Support: 0.45
Rule: nan -> wine
Support: 0.3
Rule: nan -> wine
Support: 0.45
Rule: Chips -> Apple
Support: 0.35
Rule: Chips -> Apple
Support: 0.3
Rule: nan -> Chips
Support: 0.2
Rule: Chips -> Apple
Support: 0.3
Rule: Chips -> Apple
Support: 0.3
Rule: nan -> Chips
Support: 0.2
Rule: Chips -> Apple
Support: 0.25
Rule: Chips -> Apple
Support: 0.25
Rule: Apple -> milk
Support: 0.4
Rule: nan -> Apple
Support: 0.3
Rule: wine -> Apple
Support: 0.4
Rule: nan -> Apple
Support: 0.3
Rule: wine -> Apple
Support: 0.45
Rule: nan -> wine
Support: 0.35
Rule: nan -> Apple
Support: 0.25
Rule: wine -> Apple
Support: 0.35
Rule: nan -> wine
Support: 0.2
Rule: nan -> wine
Support: 0.25
Rule: Chips -> milk
Support: 0.25
Rule: nan -> Chips
Support: 0.15
Rule: wine -> Chips
Support: 0.25
Rule: wine -> Chips
Support: 0.25
Rule: wine -> Chips
Support: 0.2
Rule: nan -> milk
Support: 0.3
Rule: wine -> milk
Support: 0.4
Rule: nan -> wine
Support: 0.25
Rule: nan -> wine
Support: 0.3
Rule: nan -> wine
Support: 0.25
Rule: Chips -> Apple
Support: 0.25
Rule: Chips -> Apple
Support: 0.15
Rule: Chips -> Apple
Support: 0.25
Rule: Chips -> Apple
Support: 0.1
Rule: Chips -> Apple
Support: 0.25
Rule: Chips -> Apple
Support: 0.1
Rule: Chips -> Apple
Support: 0.1
Rule: Chips -> Apple
Support: 0.2
Rule: Apple -> butter
Support: 0.2
Rule: Apple -> butter
Support: 0.35
Rule: Apple -> butter
Support: 0.2
Rule: Apple -> nan
Support: 0.25
Rule: Chips -> butter
Support: 0.2
Rule: butter -> nan
Support: 0.2
Rule: Chips -> Apple
Support: 0.2
Rule: Apple -> butter
Support: 0.15

In [45]:
print("confidence: " + str(item[2][0][2]))
print("Lift: " + str(item[2][0][3]))

confidence: 0.2727272727272727
Lift: 1.0909090909090908

**PERCOBAAN 2**

In [7]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=07bc3b91ec5f7d5c2cb4cd8c059a9d16bc370683a14437632ba3b09f4ec3d45d
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [8]:
import numpy as np
import pandas as pd
from apyori import apriori

**Tambahkan file data_AR.xlxs**

In [9]:
from google.colab import files
uploaded = files.upload()

Saving Groceries_dataset.csv to Groceries_dataset (1).csv

**Panggil data yang telah ditambahkan**

In [10]:
data = pd.read_csv('Groceries_dataset.csv')
data.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

**Cek Ukuran data**

In [11]:
data.shape

(38765, 3)

**Mengambil isi data dan menjadikan dalam bentuk tipe data list**

In [17]:
records = []
for i in range(0, 6):
  records.append([str(data.values[i,j]) for j in range(0, 3)])

In [18]:
print(records)

[['1808', '21-07-2015', 'tropical fruit'], ['2552', '05-01-2015', 'whole milk'], ['2300', '19-09-2015', 'pip fruit'], ['1187', '12-12-2015', 'other vegetables'], ['3037', '01-02-2015', 'whole milk'], ['4941', '14-02-2015', 'rolls/buns']]

**Jalankan metode apriori untuk mendapatkan rule**

In [19]:
association_rules = apriori(records,
                            min_support=0.1,
                            min_confidence=0.2,
                            min_lift=1.0,
                            min_length=2)
association_results = list(association_rules)

**Lihat rule yang terbentuk**

In [20]:
assoc_rule = list(association_results)
print(assoc_rule)

[RelationRecord(items=frozenset({'whole milk'}), support=0.3333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole milk'}), confidence=0.3333333333333333, lift=1.0)]), RelationRecord(items=frozenset({'01-02-2015', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'01-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '01-02-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'01-02-2015'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'05-01-2015', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'05-01-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '05-01-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'05-01-2015'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'1187', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '1187'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'14-02-2015', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'rolls/buns', '14-02-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'1808', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '1808'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', '19-09-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'19-09-2015', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'2552'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'whole milk', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'3037'}), confidence=0.5, lift=3.0)]), RelationRecord(items=frozenset({'rolls/buns', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '01-02-2015', '3037'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'01-02-2015'}), items_add=frozenset({'whole milk', '3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'3037'}), items_add=frozenset({'whole milk', '01-02-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'01-02-2015', '3037'}), confidence=0.5, lift=3.0), OrderedStatistic(items_base=frozenset({'01-02-2015', '3037'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk', '01-02-2015'}), items_add=frozenset({'3037'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk', '3037'}), items_add=frozenset({'01-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'whole milk', '05-01-2015', '2552'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'05-01-2015'}), items_add=frozenset({'whole milk', '2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2552'}), items_add=frozenset({'whole milk', '05-01-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk'}), items_add=frozenset({'05-01-2015', '2552'}), confidence=0.5, lift=3.0), OrderedStatistic(items_base=frozenset({'05-01-2015', '2552'}), items_add=frozenset({'whole milk'}), confidence=1.0, lift=3.0), OrderedStatistic(items_base=frozenset({'whole milk', '05-01-2015'}), items_add=frozenset({'2552'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'whole milk', '2552'}), items_add=frozenset({'05-01-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'other vegetables', '1187', '12-12-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1187'}), items_add=frozenset({'other vegetables', '12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'12-12-2015'}), items_add=frozenset({'other vegetables', '1187'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables'}), items_add=frozenset({'1187', '12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'1187', '12-12-2015'}), items_add=frozenset({'other vegetables'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables', '1187'}), items_add=frozenset({'12-12-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'other vegetables', '12-12-2015'}), items_add=frozenset({'1187'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'rolls/buns', '14-02-2015', '4941'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'14-02-2015'}), items_add=frozenset({'rolls/buns', '4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'4941'}), items_add=frozenset({'rolls/buns', '14-02-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns'}), items_add=frozenset({'14-02-2015', '4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'14-02-2015', '4941'}), items_add=frozenset({'rolls/buns'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns', '14-02-2015'}), items_add=frozenset({'4941'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'rolls/buns', '4941'}), items_add=frozenset({'14-02-2015'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'tropical fruit', '1808', '21-07-2015'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'1808'}), items_add=frozenset({'tropical fruit', '21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'21-07-2015'}), items_add=frozenset({'tropical fruit', '1808'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit'}), items_add=frozenset({'1808', '21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'1808', '21-07-2015'}), items_add=frozenset({'tropical fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit', '1808'}), items_add=frozenset({'21-07-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'tropical fruit', '21-07-2015'}), items_add=frozenset({'1808'}), confidence=1.0, lift=6.0)]), RelationRecord(items=frozenset({'2300', '19-09-2015', 'pip fruit'}), support=0.16666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'19-09-2015'}), items_add=frozenset({'2300', 'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300'}), items_add=frozenset({'19-09-2015', 'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'pip fruit'}), items_add=frozenset({'2300', '19-09-2015'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300', '19-09-2015'}), items_add=frozenset({'pip fruit'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'19-09-2015', 'pip fruit'}), items_add=frozenset({'2300'}), confidence=1.0, lift=6.0), OrderedStatistic(items_base=frozenset({'2300', 'pip fruit'}), items_add=frozenset({'19-09-2015'}), confidence=1.0, lift=6.0)])]

**Lihat banyaknya rule yang terbentuk**

In [21]:
print(len(assoc_rule))

25

**Rule yang terbentuk lebih detail**

In [22]:
for item in assoc_rule:
    pair = item[0]
    items = [x for x in pair]

    if len(items) > 1:
        print("Rule: " + items[0] + " -> " + items[1])
        print("Support: " + str(item[1]))

Rule: 01-02-2015 -> 3037
Support: 0.16666666666666666
Rule: whole milk -> 01-02-2015
Support: 0.16666666666666666
Rule: 05-01-2015 -> 2552
Support: 0.16666666666666666
Rule: whole milk -> 05-01-2015
Support: 0.16666666666666666
Rule: 1187 -> 12-12-2015
Support: 0.16666666666666666
Rule: other vegetables -> 1187
Support: 0.16666666666666666
Rule: other vegetables -> 12-12-2015
Support: 0.16666666666666666
Rule: 14-02-2015 -> 4941
Support: 0.16666666666666666
Rule: rolls/buns -> 14-02-2015
Support: 0.16666666666666666
Rule: 1808 -> 21-07-2015
Support: 0.16666666666666666
Rule: tropical fruit -> 1808
Support: 0.16666666666666666
Rule: 2300 -> 19-09-2015
Support: 0.16666666666666666
Rule: 19-09-2015 -> pip fruit
Support: 0.16666666666666666
Rule: tropical fruit -> 21-07-2015
Support: 0.16666666666666666
Rule: 2300 -> pip fruit
Support: 0.16666666666666666
Rule: whole milk -> 2552
Support: 0.16666666666666666
Rule: whole milk -> 3037
Support: 0.16666666666666666
Rule: rolls/buns -> 4941
Support: 0.16666666666666666
Rule: whole milk -> 01-02-2015
Support: 0.16666666666666666
Rule: whole milk -> 05-01-2015
Support: 0.16666666666666666
Rule: other vegetables -> 1187
Support: 0.16666666666666666
Rule: rolls/buns -> 14-02-2015
Support: 0.16666666666666666
Rule: tropical fruit -> 1808
Support: 0.16666666666666666
Rule: 2300 -> 19-09-2015
Support: 0.16666666666666666

In [23]:
print("confidence: " + str(item[2][0][2]))
print("Lift: " + str(item[2][0][3]))

confidence: 1.0
Lift: 6.0